version: 3.9

services:
  db:
    image: postgres:15.6-alpine
    restart: always
    environment:
      - POSTGRES_USER: potgres
      - POSTGRES_PASSWORD: 1234
      - POSTGRES_DATABASE: inno_db
    
    ports:
      - '5432:5432'

    volumes:
      - db:/var/lib/postgresql/data
    
    